
name: MyPy

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/mypy.yml'
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/mypy.yml'
      - 'src/**'

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    name: MyPy ${{ matrix.python-version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Tools (Wheel, Setuptools, MyPy)
        run: |
          python -m pip install wheel setuptools mypy
      - name: Build & Install Repo
        run: |
          python -m pip install .
      - name: Run MyPy
        run: |
          mypy --config-file mypy.ini -p serialization_tools